### ISSUE TITLE
RE: Hello Sir/Seth

### ISSUE THREAD

**Issue by silver2row** [imfatant/test#10]
Hello,

This is my error now.

    RCOutputAioPRU.cpp:SIGBUS error generated

...

I followed your info. and I attempted to change and "hack" my way to success. I have been unable to make a workaround just yet.

...

Seth

**Comment by imfatant** [comment]
Hi Seth,

The most likely reason is that you haven't quite followed step 7 exactly. Try recopying am335x-boneblue.dtb (from the bin directory in this repo) to /boot/dtbs/4.4.113-ti-rt-r149.

It's all I can really think of.

Hope it works out for you.
