### ISSUE TITLE
Unable to install future 

### ISSUE THREAD

**Issue by 7st4r** [imfatant/test#12]
Hi i am unable to install future, any idea how i can fix it? Here is the log 

debian@beaglebone:~$ sudo pip install future
Collecting future
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
    100% |################################| 829kB 113kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-PRquLf/future/setup.py", line 181, in <module>
        **setup_kwds
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/setuptools/dist.py", line 258, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 2065, in load
        raise ImportError("%r has no %r attribute" % (entry,attr))
    ImportError: <module 'setuptools.dist' from '/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/setuptools/dist.pyc'> has no 'check_specifier' attribute
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-PRquLf/future/
debian@beaglebone:~$

**Comment by imfatant** [comment]
I manually re-checked the whole ArduPilot install from scratch, with no problem. Have you followed the entire guide?

**Comment by 7st4r** [comment]
Jah i did,


These are the challenges I faced.


- The console image wouldn't work at all so i hade to use the iot version.

- Future wouldn't install and as a result waf wouldn't work.

- I installed it on one occasion to work but didn't have any indication if it was running as it wouldn't connect Qgroundcontroll or APM planer.


Would it have been possible to do a youtube version of the install og running process? I know many would have appraciated it.


Best regards


________________________________

**Comment by imfatant** [comment]
Hi,

I've never made a YouTube video before. That would take a bunch of time...

Like I said, I verified the guide completely yesterday. It works perfectly.
I don't understand where you are going wrong if you follow it exactly.

The guide is intended as a bare bones installation using a console image,
so that there's a minimum or processes running. This makes it easier to see
what's going on should one want to look at problems like boot time etc.
When you say that you couldn't get the console image to work, what
precisely do you mean? Perhaps starting there would be the best approach.

The IoT image already has ArduPilot, so you shouldn't need the guide.

-- Anthony

**Comment by 7st4r** [comment]
I installed the console image on micro sd, tried booting from there. I get Blue LED flashing but i cant connect to the board with ssh or claud9. I tried with IOT image and i was able to connect and follow all the instructions in your giude. I will give it a try this evening again.


Thank you for your respons.



________________________________

**Comment by imfatant** [comment]
What OS are you using? Windows or Linux, and if Linux, which distro?

**Comment by 7st4r** [comment]
I am using Mac so linux i suppose, i used itche to write the image. Not sure if that answered the info you asked?

**Comment by 7st4r** [comment]
So to be able to connect with q ground control do i only needed to

TELEM1="-C /dev/ttyO1"
TELEM2="-A udp:<target IP address>:14550"
GPS="-B /dev/ttyS2"

with my mac wlan ip adress? 
Or is there any command that can check if the program is running?

**Comment by imfatant** [comment]
Yes, there's commands to check that ArduPilot is running (`ps aux` or
`systemctl`), but it's simpler to see if the red LED is flashing on the
BBBlue. This means ArduPilot (arducopter, etc) is running. If it's not on,
it's not running.

Use:

TELEM1="-C /dev/ttyO1"
TELEM2="-A udp:<target IP address>:14550"
GPS="-B /dev/ttyS2"

Where you replace <target IP address> with your Mac's IP on your local
network.

**Comment by 7st4r** [comment]
The red LED isnt flashing

**Comment by imfatant** [comment]
Then it ain't running.

**Comment by imfatant** [comment]
And by the way, I do recommend Etcher for creating images.

**Comment by 7st4r** [comment]
i just now created an image with etcher on sd card and and trying to reboot from it but i can ssh the board or claod9 it

**Comment by imfatant** [comment]
I should also say, that departing from the guide, even in tiny ways, is NOT
recommended. I wrote the guide because this is is NOT EASY, and many people
struggle. Those who have had problems have departed from the guide.

**Comment by 7st4r** [comment]
ok, i guess i should try it all over again

**Comment by 7st4r** [comment]
have you also treid Mirkos method?

**Comment by imfatant** [comment]
Mirko's method is effectively the same, once you know what you are doing.
My method just formalises his.

I am surprised you can't ssh to the BBBlue. You should be able to do that
without any problems if you are using the recommended image. I wonder why
you are having trouble...

**Comment by 7st4r** [comment]
My suspiction is the board isnt correctly running the console image.

**Comment by 7st4r** [comment]
Its ok with iot image

**Comment by 7st4r** [comment]
ssh debian@10.0.0.10
ssh: connect to host 10.0.0.10 port 22: Operation timed out

**Comment by imfatant** [comment]
Can I ask why you aren't connecting using ssh debian 192.168.7.2 ?

**Comment by imfatant** [comment]
I mean debian@192.168.7.2

**Comment by 7st4r** [comment]
I treid that too

**Comment by imfatant** [comment]
But why did you use 10.0.0.10? I'm curious. And since we're trying to track
down a problem, I must ask..

**Comment by imfatant** [comment]
Have you installed the Mac drivers?
https://learn.adafruit.com/ssh-to-beaglebone-black-over-usb/installing-drivers-mac

**Comment by 7st4r** [comment]
10.0.0.10 is the beaglebone wireless ip adress. I am able to ssh debian with both 10.0.0.10 and 192.168.6.2, but not with 192.168.7.2 in the ito image. In the console image i cant ssh debain with 10.0.0.10, 192.168.7.2 or 192.168.6.2. I was able to install the network driver but not the serial driver.

**Comment by imfatant** [comment]
I have no experience of using a Mac. However, I would concentrate upon
establishing a connection to 192.168.7.2 using the console image. This is
the start of the process outlined in the guide. I don't know what else to
suggest.

**Comment by 7st4r** [comment]
I understand, I have requasted for a replacement of BBBlue from the retailer as it might be faulty. Like I mentioned i am able to connect with Iot image but not with console image.
