### ISSUE TITLE
The giud isnt working

### ISSUE THREAD

**Issue by 7st4r** [imfatant/test#14]
Hi, 

The guide said it was updated 18/03-19, but I just tried it 19/03-19 and it's not working. I followed all the steps but the board fails to inflate with flashing red LED light. I did to try to start arducopter manually and I get an error message, 
"RCOutputAioPRU.cpp:SIGBUS error generated"
Any idea what I am missing?

**Comment by imfatant** [comment]
I've had a read of the Gitter feed and I believe you've solved the problem? Cool! I'll close this issue, but please feel free to open another if you experience more problems.
