### ISSUE TITLE
Using DSM2 port with Lemon DSM2RX receiver.

### ISSUE THREAD

**Issue by tiago1405** [imfatant/test#17]
I am trying to setup and calibrate the radio controller using a Lemon DSM2RX, Blade MLP4DSM Controller, and QGroundControl (V.3.5.0). The ground control detects the BeagleBone running Arducopter, however when calibrating the controller it doesnt seem to detect my controller. I made the "-C" option in the /etc/default/ardupilot set to "ttyO4" for the DSM2 (UART4) slot on the beagle. Is there anything I'm missing?

**Comment by tiago1405** [comment]
The contents of my /etc/default/ardupilot file:

TELEM1="-C /dev/ttyO4"
TELEM2="-A udp:10.1.192.219:14550"
GPS="-B /dev/ttyS2"

**Comment by imfatant** [comment]
Hi,

You connect DSM to connector E4 pin 4, not UART4.

Hope that helps.

-- Imf

**Comment by imfatant** [comment]
Hang on.. let me check. You might be right.

**Comment by imfatant** [comment]
OK, sorry about my confusion. I use SBUS on Pin 4 of connector E4. I have not tried the DSM UART.

TELEM1 does not do what you think it does. It supplies (outputs) telemetry data using the MAVLink protocol. The R/C receiver is nothing to do with the /etc/default/ardupilot file.

The problem is that I only have experience of SBUS. I know  of a couple of people who have used Spektrum/DSM systems successfully, but I cannot speak for Lemon. Until now, I'd never heard of them :)
I'm not sure what I can suggest, other than to assure you that if QGroundControl is picking up the BBBlue, the problem is unlikely to be to do with QGroundControl, but you could try Mission Planner instead (only Windows)?

**Comment by tiago1405** [comment]
Ok, so would I need to do any setup in the Linux for connector E4 pin 4? I tried to rig that up using power and ground from the pwr connector and pin4 from E4 directly into my Lemon DSM2Rx.
Is there also any way to just control the drone through the ground station software? (I am going to a hobby store later today to look at more receivers so if you have any suggestions it would be greatly appreciated!)

**Comment by tiago1405** [comment]
Ok, so would I need to do any setup in the Linux for connector E4 pin 4? I tried to rig that up using power and ground from the pwr connector and pin4 from E4 directly into my Lemon DSM2Rx.
Is there also any way to just control the drone through the ground station software? (I am going to a hobby store later today to look at more receivers so if you have any suggestions it would be greatly appreciated!)

**Comment by imfatant** [comment]
Hi,

You should try both SBUS pins (to see if one works). These are marked on the pinout diagram.

There is no Linux software setup required for this.

Yes, there is a way to control the drone through the GC software - you can use manual mode, or various autopilot modes. You should begin by reading (all) the ardupilot documentation on ardupilot.org.

FrSky gear is good, and you can combine this with modules like Crossfire. But don't give up on your Lemon gear. There's a great deal of information out there, and it takes quite a bit of time to absorb.

**Comment by tiago1405** [comment]
So, I got a new receiver which is a Spektrum SPMAR410 DSM2/DSMX 4CH, and I got it powered and binded to the remote. Should I be good to power up the ESC and control it now? (QGC still doesn't seem to be able to complete radio calibration for some reason).

**Comment by imfatant** [comment]
You need to get the radio working first before you play around with the ESC's and motors. By the way, the Rx pin on the DSM UART is the one I'd recommend you try first.
