### ISSUE TITLE
RE: Hello!

### ISSUE THREAD

**Issue by silver2row** [imfatant/test#6]
Hello Sir,

Part I has the console image broken in a link. I tried to get to it. It either no longer exists or it has moved.

Seth

P.S. Please reply when you have time. I am still using an older image, rt 4.4.x.

**Comment by androidocean** [comment]
I have the same question. Which image should be used? 
And should the BeagleBone Blue's  emmc flash get flashed with this image,or should it be booted from microSD? Thank you for your time and assistance.

Trent

**Comment by imfatant** [comment]
Hi,

Sorry about the delay. I've fixed the link to a working version. This will likely change in a few days again.

You can do both - whatever suits you.
