### ISSUE TITLE
Image is missing from download link. Which image is recommended?

### ISSUE THREAD

**Issue by androidocean** [imfatant/test#7]
Hello imfatant,

Thank you for sharing this tutorial. The link that you shared containing the specific image that you used

[https://rcn-ee.net/rootfs/bb.org/testing/2018-07-15/stretch-console/bone-debian-9.5-console-armhf-2018-07-15-1gb.img.xz](url)

is no longer available. 

Which image is recommended? 
And should that image be flashed to the eMMC storage or booted from the microSD?
Thank you for your time and help.

Trent

**Comment by imfatant** [comment]
Hi,

Sorry about the delay. I've fixed the link to a working version. This will likely change in a few days again.
