### ISSUE TITLE
Will the DSM2 Port work with ardupilot blue?

### ISSUE THREAD

**Issue by androidocean** [imfatant/test#9]
Hello imfatant
Will the ardupilot blue image support the DSM2 plug on the BBBl, Or is it necessary to connect the dsm satellite receiver to other pins on Blue?

I have a Lemon RX DSM2 Satellite Reciever that is confirmed to work with the DSM2 Port using libroboticscape code on the iot image. I was able to bind and calibrate a Blade MLP4DSM Spectrum Compatable Transmitter with the Lemon Reciever using the examples provided with libroboticscape.

It would be great if this Reciever would work with the ardupilot blue image. I noticed from mirkix tutorial that his DSM Satellite is not connected to the DSM2 Port on the BBBl. In his photo it appears there is a single wire to one of the quad encoder pins. 

Thanks for your time
Trent

**Comment by imfatant** [comment]
Both should work. I believe we had a chap on the Gitter forum successfully use the DSM2 plug. Is there any reason why you can't just connect it and see?
